#!/bin/bash

# Jacob Feder jacobsfeder@gmail.com
# 1/29/2018

# automated build system for Zynq SoC projects

# ----------------------------------------------------------
# ----------------------------------------------------------
# ----------------------------------------------------------

usage() { echo "Usage: xilmake [options] [project directory]
Description: Automated build system for Zynq SoC projects.

--------------------------------------------------------------------------------

Arguments:

	-c, --menuconfig [g, r, k]
		Bring up the menu for manual configuration during compilation
		for each of the given arguments. Pass the letter of the
		corresponding configs in any order.

		g = general config
		r = rootfs config
		k = kernel config

		Also copies the general and rootfs config files into the source
		directory (/src/linux/config/saved_configs/config-last and
		/src/linux/config/saved_configs/rootfs_config-last).

	-d, --download [SD card file]
		Download boot files to an SD card (e.g. /dev/sdc).
		Does not perform any build steps unless an --from or
		--to option is specified.

	--format
		Format an SD card with boot, rootfs, and storage partitions
		before downloading (must be used with -d option)

	-f,  --from [see below]
		The build step to start at. Assumed to be
		1 if not specified.

	-h, --help
		Show this help menu.

	-i, --ignore
		Skip steps that would overwrite previously completed
		build steps if specified by --from, --to.

	-o, --overwrite
		Overwrite files from previously completed
		build steps if specified by -from, -to.

	-p, --project [name string]
		Use this for different project build variants.

	-t,  --to [see below]
		The build step to stop at (inclusive). Assumed to be the
		last build step if not specified.

--------------------------------------------------------------------------------

Build steps:

na - if you don't want to perform any build steps use --from na --to na
ip - generate and package IP from source (create Vivado IP projects &
	package IP)
vg - generate Vivado project from source & IP (import IP, generate main
	Vivado project from source and block diagram tcl script)
vb - build Vivado project (synthesis + implementation + generate bitstream +
	export bitstream)
lg - generate linux project (petalinux-create project,
	petalinux-create modules/apps)
lc - linux config (petalinux-config)
ls - copy linux sources (copy source files petalinux directories)
lb - build linux project (petalinux-build + petalinux-package)

--------------------------------------------------------------------------------

Notes:

Supports the following linux rootfs types:
- initramfs
- initrd
- SD boot (use xilmake -d to download the rootfs to the SD card)

If Vivado build (vb) is run and linux has already been built,
petalinux-package will be run with the most recent bitstream file.
This can decrease build time if only FPGA firmware that doesn't
interface with the PS was modified.

--------------------------------------------------------------------------------

Examples:

# generate & package IP
xilmake -f ip -t ip .
# or
xilmake -tip ~/zynq/cool_project

# generate and build Vivado/FPGA design, creating the bit file directly without
# any linux compilation
xilmake -f ip -t vb .

# generate and build linux from existing Vivado hardware design and also bring
# up the manual config menu for general and rootfs configs
xilmake -flg -tlb -cgr .
# or
xilmake -flg -cgr .

# generate and build linux from existing Vivado hardware design then download
# boot files to SD card /dev/sdc
xilmake -f lg -d /dev/sdc .

# generate and build entire project and download boot files to SD card
xilmake -tlb -d /dev/sdc .

# download previously generated boot files
# to SD card /dev/sdb
xilmake -d /dev/sdb ." 1>&2; exit 1; }

# ----------------------------------------------------------
# ----------------------- build steps ----------------------
# ----------------------------------------------------------

NA=0
IP=1
VG=2
VB=3
LG=4
LC=5
LS=6
LB=7

# ----------------------------------------------------------
# ---------------------- read options ----------------------
# ----------------------------------------------------------

TEMP=`getopt -o c:d:f:hiop:t: --long menuconfig:,download:,format,from:,help,ignore,overwrite,project:,to: -n "xilmake" -- "$@"`
eval set -- "$TEMP"

# TODO linux quick build option that runs script to gcc compile + sftp
# TODO wireless update w/ sftp
# TODO NFS

# extract options and their arguments into variables.
while true ; do
	case $1 in
		-c|--menuconfig)
			if [[ $2 = *"g"* ]]; then
				LINUX_MANUAL_CONFIG_GENERAL=1
			fi
			if [[ $2 = *"r"* ]]; then
				LINUX_MANUAL_CONFIG_ROOTFS=1
			fi
			if [[ $2 = *"k"* ]]; then
				LINUX_MANUAL_CONFIG_KERNEL=1
			fi
			if ! [[ LINUX_MANUAL_CONFIG_GENERAL && LINUX_MANUAL_CONFIG_ROOTFS && LINUX_MANUAL_CONFIG_KERNEL ]]; then
				echo "No menuconfig -c items specified"
				exit 1
			else
				shift 2
			fi ;;
		-d|--download)
			SD_CARD=$2 ; shift 2 ;;
		--format)
			FORMAT_SD_CARD=1 ; shift ;;
		-f|--from)
			case $2 in
				na) FROM=$NA ; TO=$NA ; shift 2 ;;
				ip) FROM=$IP ; shift 2 ;;
				vg) FROM=$VG ; shift 2 ;;
				vb) FROM=$VB ; shift 2 ;;
				lg) FROM=$LG ; shift 2 ;;
				lc) FROM=$LC ; shift 2 ;;
				ls) FROM=$LS ; shift 2 ;;
				lb) FROM=$LB ; shift 2 ;;
				*) echo "Unrecognized --from option $1"; exit 1 ;;
			esac ;;
		-h|--help) usage ; shift ;;
		-i|--ignore) OVERWRITE=2 ; shift ;;
		-o|--overwrite) OVERWRITE=1 ; shift ;;
		-p|--project)
			PROJECT_NAME=$2 ; shift 2 ;;
		-t|--to)
			case $2 in
				na) TO=$NA ; FROM=$NA ; shift 2 ;;
				ip) TO=$IP ; shift 2 ;;
				vg) TO=$VG ; shift 2 ;;
				vb) TO=$VB ; shift 2 ;;
				lg) TO=$LG ; shift 2 ;;
				lc) TO=$LC ; shift 2 ;;
				ls) TO=$LS ; shift 2 ;;
				lb) TO=$LB ; shift 2 ;;
				*) echo "Unrecognized --to option $1"; exit 1 ;;
			esac ;;
		--) shift ; break ;;
		*) echo "Unrecognized option $1" ; exit 1 ;;
	esac
done

# ----------------------------------------------------------
# ---------------------- set defaults ----------------------
# ----------------------------------------------------------


if [[ ! -z $SD_CARD && -z $FROM && -z $FROM ]]; then
	# if SD card is specified but not FROM or TO
	FROM=$NA
	TO=$NA
else
	# default build step to start at
	if [[ -z $FROM ]]; then
		FROM=$IP
	fi

	# default build step to stop at
	if [[ -z $TO ]]; then
		TO=$LB
	fi
fi

if [[ -z  $LINUX_MANUAL_CONFIG_GENERAL ]]; then
	# 0 to use default configs, 1 to bring up dialog
	LINUX_MANUAL_CONFIG_GENERAL=0
fi

if [[ -z  $LINUX_MANUAL_CONFIG_ROOTFS ]]; then
	# 0 to use default configs, 1 to bring up dialog
	LINUX_MANUAL_CONFIG_ROOTFS=0
fi

if [[ -z  $LINUX_MANUAL_CONFIG_KERNEL ]]; then
	# 0 to use default configs, 1 to bring up dialog
	LINUX_MANUAL_CONFIG_KERNEL=0
fi

if [[ -z  $OVERWRITE ]]; then
	# if requested to build something that already exists
	# 0 to ask, 1 to overwrite, anything else to skip
	OVERWRITE=0
fi

# ----------------------------------------------------------
# ------- project file/dir locations + error checks --------
# ----------------------------------------------------------

if [[ -z $1 ]]; then
	echo "No project directory specified"
	exit 1
fi

OG_DIR=$PWD
TOP_DIR=$(readlink -f $1)

# source project settings
source $TOP_DIR"/settings.sh"

if [[ -z $PROJECT_NAME ]]; then
	PROJECT_NAME=$DEFAULT_PROJECT_NAME
fi

PROJECT_BUILD_DIR=$TOP_DIR"/build/"$PROJECT_NAME
IP_PROJECT_NAME=$PROJECT_NAME"_IP"
IP_PROJECT_DIR=$PROJECT_BUILD_DIR"/"$IP_PROJECT_NAME
VIVADO_PROJECT_NAME=$PROJECT_NAME"_hw"
VIVADO_PROJECT_DIR=$PROJECT_BUILD_DIR"/"$VIVADO_PROJECT_NAME
HDF_FILE=$VIVADO_PROJECT_DIR"/"$PROJECT_NAME".hdf"
BIT_FILE=$VIVADO_PROJECT_DIR"/"$PROJECT_NAME".bit"
LINUX_PROJECT_NAME=$PROJECT_NAME"_linux"
LINUX_PROJECT_DIR=$PROJECT_BUILD_DIR"/"$LINUX_PROJECT_NAME

if ! [[ -d $TOP_DIR ]]; then
	echo "Specified project directory $1 does not exist"
	exit 1
fi

if ! [[ -e $TOP_DIR"/settings.sh" ]]; then
	echo "Specified project directory has no settings.sh file"
	echo $TOP_DIR"/settings.sh"
	exit 1
fi

# ----------------------------------------------------------
# -------------------- initial setup -----------------------
# ----------------------------------------------------------

START_TIME="$(date -u +%s)"

# add required tools to PATH
if ! [[ $FROM -gt $VB || $TO -lt $IP ]]; then
	source $VIVADO_INSTALL_DIR"/settings64.sh"
fi
if ! [[ $FROM -gt $LB || $TO -lt $LG ]]; then
	source $PETALINUX_INSTALL_DIR"/settings.sh" $PETALINUX_INSTALL_DIR
fi

# create main build directory
if [[ ! -e $PROJECT_BUILD_DIR ]]; then
	mkdir -p $PROJECT_BUILD_DIR
fi

# ----------------------------------------------------------
# -- generate and package project-specific IP from source --
# ----------------------------------------------------------

if [[ $FROM -le $IP && $TO -ge $IP ]]; then
	# check if step has already been performed
	if [[ -e $IP_PROJECT_DIR ]]; then
		if [[ $OVERWRITE -eq 0 ]]; then
			# ask to overwrite
			read -p "Overwrite previously generated IP? (y / n)" yn
			case $yn in
				[Yy]* ) OVERWRITE=1 ;;
				* ) OVERWRITE=0 ;;
			esac
		fi

		if [[ $OVERWRITE -eq 1 ]]; then
			# overwrite
			rm -rf $IP_PROJECT_DIR
			SKIP=0
		else
			# skip
			echo "--------------------------------"
			echo "Skipping IP generation/packaging"
			echo "--------------------------------"
			SKIP=1
		fi
	else
		SKIP=0
	fi

	if [[ $SKIP -eq 0 ]]; then
		echo "---------------------------"
		echo "Generating and packaging IP"
		echo "---------------------------"

		mkdir $IP_PROJECT_DIR

		cd $TOP_DIR"/src/hdl/ip"
		for ip_src_dir in */ ; do
			echo "Building IP "$ip_src_dir
			echo "-----------------"
			
			expanded_ip_src_dir=$(readlink -f $TOP_DIR"/src/hdl/ip/"$ip_src_dir)
			
			vivado -mode batch -nojournal -nolog -notrace -source $ip_src_dir"generate.tcl" -tclargs $IP_PROJECT_DIR $expanded_ip_src_dir $BOARD_NAME
			
			echo "Built IP "$ip_src_dir
			echo "-----------------"
		done
	fi
fi

# ----------------------------------------------------------
# -------- generate Vivado project from source & IP --------
# ----------------------------------------------------------

if [[ $FROM -le $VG && $TO -ge $VG ]]; then
	# check if step has already been performed
	if [[ -e $VIVADO_PROJECT_DIR ]]; then
		if [[ $OVERWRITE -eq 0 ]]; then
			# ask to overwrite
			read -p "Overwrite previously generated Vivado project? (y / n)" yn
			case $yn in
				[Yy]* ) OVERWRITE=1 ;;
				* ) OVERWRITE=0 ;;
			esac
		fi

		if [[ $OVERWRITE -eq 1 ]]; then
			# overwrite
			rm -rf $VIVADO_PROJECT_DIR
			SKIP=0
		else
			# skip
			echo "----------------------------------"
			echo "Skipping Vivado project generation"
			echo "----------------------------------"
			SKIP=1
		fi
	else
		SKIP=0
	fi

	if [[ $SKIP -eq 0 ]]; then
		echo "-------------------------"
		echo "Generating Vivado project"
		echo "-------------------------"

		mkdir $VIVADO_PROJECT_DIR

		vivado -mode batch -nojournal -nolog -notrace -source $TOP_DIR"/src/hdl/generate.tcl" -tclargs $VIVADO_PROJECT_NAME $PROJECT_BUILD_DIR $IP_PROJECT_DIR $TOP_DIR"/src/hdl/" $BOARD_NAME $VIVADO_GENERATE_ARGS
	fi
fi

# ----------------------------------------------------------
# ------------------ build Vivado project ------------------
# ----------------------------------------------------------

if [[ $FROM -le $VB && $TO -ge $VB ]]; then
	# check if step has already been performed
	if [[ -e $HDF_FILE ]]; then
		if [[ $OVERWRITE -eq 0 ]]; then
			# ask to overwrite
			read -p "Overwrite previous Vivado project build? (y / n)" yn
			case $yn in
				[Yy]* ) OVERWRITE=1 ;;
				* ) OVERWRITE=0 ;;
			esac
		fi

		if [[ $OVERWRITE -eq 1 ]]; then
			# overwrite
			rm -rf $VIVADO_PROJECT_DIR"/"$VIVADO_PROJECT_NAME".runs"
			rm -f $HDF_FILE
			SKIP=0
		else
			# skip
			echo "-----------------------------"
			echo "Skipping Vivado project build"
			echo "-----------------------------"
			SKIP=1
		fi
	else
		SKIP=0
	fi

	if [[ $SKIP -eq 0 ]]; then
		echo "-----------------------"
		echo "Building Vivado project"
		echo "-----------------------"
		
		echo "open_project "$VIVADO_PROJECT_DIR"/"$VIVADO_PROJECT_NAME".xpr" \
			 $'\nlaunch_runs synth_1 -jobs 8\nwait_on_run synth_1\nlaunch_runs impl_1 -jobs 8' \
			 $'\nwait_on_run impl_1\nlaunch_runs impl_1 -to_step write_bitstream -jobs 8\nwait_on_run impl_1' > $PROJECT_BUILD_DIR"/build.tcl"
		vivado -mode batch -nojournal -nolog -notrace -source $PROJECT_BUILD_DIR"/build.tcl"

		cp -f $VIVADO_PROJECT_DIR"/"$VIVADO_PROJECT_NAME".runs/impl_1/"$VIVADO_PROJECT_NAME"_wrapper.sysdef" $HDF_FILE
		cp -f $VIVADO_PROJECT_DIR"/"$VIVADO_PROJECT_NAME".runs/impl_1/"$VIVADO_PROJECT_NAME"_wrapper.bit" $BIT_FILE

		rm -f $PROJECT_BUILD_DIR"/build.tcl"

		# if linux has already been built and won't be rebuilt,
		# petalinux-package to copy over the new bit file
		if [[ -e $LINUX_PROJECT_DIR"/images/linux/" && $TO -lt 6 ]]; then
			echo "-----------------------"
			echo "Packaging Linux project"
			echo "-----------------------"

			cd $LINUX_PROJECT_DIR

			# begin virtual python environment to force python2 usage for bitbake
			virtualenv -p /usr/bin/python2.7 --distribute temp-python
			source temp-python/bin/activate

			# package boot files
			petalinux-package --boot --fsbl $LINUX_PROJECT_DIR"/images/linux/zynq_fsbl.elf" --fpga $BIT_FILE --u-boot --force	

			# stop & remove virtual python environment
			deactivate
			rm -rf temp-python
		fi
	fi
fi

# ----------------------------------------------------------
# ----------------- generate linux project -----------------
# ----------------------------------------------------------

if [[ $FROM -le $LG && $TO -ge $LG ]]; then
	# check if step has already been performed
	if [[ -e $LINUX_PROJECT_DIR ]]; then
		if [[ $OVERWRITE -eq 0 ]]; then
			# ask to overwrite
			read -p "Overwrite previously generated linux project? (y / n)" yn
			case $yn in
				[Yy]* ) OVERWRITE=1 ;;
				* ) OVERWRITE=0 ;;
			esac
		fi

		if [[ $OVERWRITE -eq 1 ]]; then
			# overwrite
			rm -rf $LINUX_PROJECT_DIR
			SKIP=0
		else
			# skip
			echo "-------------------------------"
			echo "Skipping Linux project generate"
			echo "-------------------------------"
			SKIP=1
		fi
	else
		SKIP=0
	fi

	if [[ $SKIP -eq 0 ]]; then
		echo "------------------------"
		echo "Generating Linux project"
		echo "------------------------"
		
		cd $PROJECT_BUILD_DIR

		# create petalinux project
		petalinux-create --type project --template zynq --name $LINUX_PROJECT_NAME
		cd $LINUX_PROJECT_DIR

		# start with default config
		petalinux-config --get-hw-description=$VIVADO_PROJECT_DIR --oldconfig

		# generate apps/modules
		source $TOP_DIR"/src/linux/generate.sh"
	fi
fi

# ----------------------------------------------------------
# ------------------ config linux project ------------------
# ----------------------------------------------------------

if [[ $FROM -le $LC && $TO -ge $LC ]]; then
	echo "-------------------------"
	echo "Configuring Linux project"
	echo "-------------------------"
	cd $LINUX_PROJECT_DIR

	if [[ ! -e $TOP_DIR"/src/linux/config/saved_configs/" ]]; then
		mkdir -p $TOP_DIR"/src/linux/config/saved_configs/"
	fi

	if [[ $LINUX_MANUAL_CONFIG_GENERAL != 0 ]]; then
		petalinux-config --get-hw-description=$VIVADO_PROJECT_DIR
		cp -f -v $LINUX_PROJECT_DIR"/project-spec/configs/config" $TOP_DIR"/src/linux/config/saved_configs/config-last"
	else
		if [[ -e $TOP_DIR"/src/linux/config/config" ]]; then
			cp -f -v $TOP_DIR"/src/linux/config/config" $LINUX_PROJECT_DIR"/project-spec/configs/"
		else
			echo "Using default general config..."
		fi
		petalinux-config --get-hw-description=$VIVADO_PROJECT_DIR --oldconfig

	fi

	if [[ $LINUX_MANUAL_CONFIG_ROOTFS != 0 ]]; then
		petalinux-config -c rootfs
		cp -f -v $LINUX_PROJECT_DIR"/project-spec/configs/rootfs_config" $TOP_DIR"/src/linux/config/saved_configs/rootfs_config-last"
	else
		if [[ -e $TOP_DIR"/src/linux/config/rootfs_config" ]]; then
			cp -f -v $TOP_DIR"/src/linux/config/rootfs_config" $LINUX_PROJECT_DIR"/project-spec/configs/"
		else
			echo "Using default rootfs config..."
		fi
		petalinux-config -c rootfs --oldconfig
	fi


	if [[ $LINUX_MANUAL_CONFIG_KERNEL != 0 ]]; then
		echo "!! ATTENTION !! kernel config file must be manually saved"
		petalinux-config -c kernel
	else
		if [[ -e $TOP_DIR"/src/linux/config/linux-xlnx_%.bbappend" ]]; then
			cp -f -v $TOP_DIR"/src/linux/config/linux-xlnx_%.bbappend" $LINUX_PROJECT_DIR"/project-spec/meta-plnx-generated/recipes-kernel/linux/"
			cp -f -v $TOP_DIR"/src/linux/config/kernel_config_fragments/"* $LINUX_PROJECT_DIR"/project-spec/meta-plnx-generated/recipes-kernel/linux/configs"
		else
			echo "Using default kernel config..."
		fi
	fi
fi

# ----------------------------------------------------------
# ------------- copy sources into linux project ------------
# ----------------------------------------------------------

if [[ $FROM -le $LS && $TO -ge $LS ]]; then
	echo "----------------------------------"
	echo "Copying sources into Linux project"
	echo "----------------------------------"
	
	# copy source files into project
	source $TOP_DIR"/src/linux/copy.sh" $TOP_DIR"/src/linux" $LINUX_PROJECT_DIR
fi

# ----------------------------------------------------------
# --- build linux project from existing project directory --
# ----------------------------------------------------------

if [[ $FROM -le $LB && $TO -ge $LB ]]; then
	echo "----------------------"
	echo "Building Linux project"
	echo "----------------------"

	cd $LINUX_PROJECT_DIR

	# begin virtual python environment to force python2 usage for bitbake
	virtualenv -p /usr/bin/python2.7 --distribute temp-python
	source temp-python/bin/activate

	# build petalinux
	petalinux-build

	# package boot files
	petalinux-package --boot --fsbl $LINUX_PROJECT_DIR"/images/linux/zynq_fsbl.elf" --fpga $LINUX_PROJECT_DIR"/images/linux/system.bit" --u-boot --force

	# stop & remove virtual python environment
	deactivate
	rm -rf temp-python
fi

# ----------------------------------------------------------
# ------------- download boot files to SD card -------------
# ----------------------------------------------------------

# SD card partition mount locations
SD_MNT_BOOT_DIR=/mnt/BOOT
SD_MNT_ROOTFS_DIR=/mnt/rootfs
SD_MNT_STORAGE_DIR=/mnt/storage

if [[ ! -z $SD_CARD ]]; then
	if [[ ! -z $FORMAT_SD_CARD ]]; then
		echo "------------------------------------------"
		echo "       Formatting SD card "$SD_CARD
		echo "------------------------------------------"

		read -p "About to erase all data on $SD_CARD and format it. Are you sure you want to continue? (y / n)" yn
		if [[ $yn == "y"* ]] ; then
			# unmount and remove all partitions
			partitions=($SD_CARD?)
			if [[ "$partitions" != $SD_CARD\? ]]; then
				for ((i=${#partitions[@]}-1; i>=0; i--)); do
					sudo umount "${partitions[$i]}"
					sudo parted $SD_CARD rm "${partitions[$i]: -1}"
				done
			fi

			# create partition table
			sudo parted $SD_CARD mklabel msdos

			# create boot partition
			sudo parted -a optimal $SD_CARD -s 'mkpart primary fat32 0% 512MB'
			# create rootfs partition
			sudo parted -a optimal $SD_CARD -s 'mkpart primary ext4 512MB 90%'
			# create storage partition
			sudo parted -a optimal $SD_CARD -s 'mkpart primary ext4 90% 100%'

			# format boot as fat32
			sudo mkfs.fat -F32 -n BOOT $SD_CARD"1"
			# format rootfs as ext4
			sudo mkfs.ext4 -F -L rootfs $SD_CARD"2"
			# format storage as ext4
			sudo mkfs.ext4 -F -L storage $SD_CARD"3"
		else
			echo "Not formatting..."
		fi
	fi

	echo "------------------------------------------"
	echo "Downloading boot files to SD card "$SD_CARD
	echo "------------------------------------------"

	if ls $SD_CARD"1" 1> /dev/null 2>&1; then
		if blkid $SD_CARD"1" | grep -q vfat ; then
			# mount boot partition
			sudo mkdir -p $SD_MNT_BOOT_DIR
			sudo mount $SD_CARD"1" $SD_MNT_BOOT_DIR

			# mount rootfs partition
			sudo mkdir -p $SD_MNT_ROOTFS_DIR
			sudo mount $SD_CARD"2" $SD_MNT_ROOTFS_DIR

			# mount storage partition
			sudo mkdir -p $SD_MNT_STORAGE_DIR
			sudo mount $SD_CARD"3" $SD_MNT_STORAGE_DIR

			# remove all previous files from partitions
			sudo rm -rf $SD_MNT_BOOT_DIR"/"*
			sudo rm -rf $SD_MNT_ROOTFS_DIR"/"*
			sudo rm -rf $SD_MNT_STORAGE_DIR"/"*

			# copy FSBL, u-boot, bitstream into boot partition
			sudo cp -f -v $LINUX_PROJECT_DIR"/images/linux/BOOT.BIN" $SD_MNT_BOOT_DIR
			# add additional u-boot environment variables into boot partition
			echo 'uenvcmd=if test -n ${ipaddr}; then tftpboot ${clobstart} system.bit; fpga loadb 0 ${clobstart} ${filesize}; run update_boot; run update_kernel; else echo "No ethernet connection, skipping TFTP update..."; fi' | sudo tee $SD_MNT_BOOT_DIR"/uEnv.txt" > /dev/null

			# copy FIT image into boot partition
			sudo cp -f -v $LINUX_PROJECT_DIR"/images/linux/image.ub" $SD_MNT_BOOT_DIR

			# decompress linux into rootfs partition
			sudo tar -xzf $LINUX_PROJECT_DIR"/images/linux/rootfs.tar.gz" -C $SD_MNT_ROOTFS_DIR

			# copy default storage files into storage partition
			sudo cp -f -v $TOP_DIR"/src/linux/storage/"* $SD_MNT_STORAGE_DIR

			# unmount partitions
			sudo umount $SD_CARD"3"
			sudo umount $SD_CARD"2"
			sudo umount $SD_CARD"1"
			sudo rm -rf $SD_MNT_BOOT_DIR
			sudo rm -rf $SD_MNT_ROOTFS_DIR
			sudo rm -rf $SD_MNT_STORAGE_DIR
		else
			echo "SD card not formatted correctly: partition 1 (boot partition) is not FAT"
		fi
	else
		echo "SD card specified was not found. Not downloading..."
	fi
fi

# ----------------------------------------------------------
# ----------------------- cleanup --------------------------
# ----------------------------------------------------------

END_TIME="$(date -u +%s)"
ELAPSED_TIME="$(($END_TIME-$START_TIME))"
((HOURS=${ELAPSED_TIME} / 3600))
((MINUTES=(${ELAPSED_TIME} % 3600) / 60))
((SECONDS=${ELAPSED_TIME} % 60))
printf "Build complete - run time %02d:%02d:%02d\n" $HOURS $MINUTES $SECONDS

cd $OG_DIR